/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 car-gnx.glb 
Author: snafuj (https://sketchfab.com/snafuj)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/1987-buick-grand-national-regal-gnx-4572494cd9cd432e8da50efb5c7a47c9
Title: 1987 Buick Grand National Regal GNX
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

const CarModel =(props)=> {
  const { nodes, materials } = useGLTF('/car-gnx.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Body} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Body} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.Body} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Body} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Body} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.Body} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.Body} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.Body} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.Body} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.Body} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.Body} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.Emission_Red} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.Fake_inside} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.Lights} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.Undercarriage} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.Undercarriage} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.Undercarriage} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.Undercarriage} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.Undercarriage} />
        <mesh geometry={nodes.Object_21.geometry} material={materials.Undercarriage} />
        <mesh geometry={nodes.Object_22.geometry} material={materials.Undercarriage} />
        <mesh geometry={nodes.Object_23.geometry} material={materials.Undercarriage} />
        <mesh geometry={nodes.Object_24.geometry} material={materials.Windows} />
        <mesh geometry={nodes.Object_25.geometry} material={materials.White_Emission_Lamp} />
        <mesh geometry={nodes.Object_26.geometry} material={materials.Wheel} />
        <mesh geometry={nodes.Object_27.geometry} material={materials.Wheel} />
        <mesh geometry={nodes.Object_28.geometry} material={materials.Wheel} />
        <mesh geometry={nodes.Object_29.geometry} material={materials.Wheel} />
        <mesh geometry={nodes.Object_30.geometry} material={materials.Wheel} />
        <mesh geometry={nodes.Object_31.geometry} material={materials.Wheel} />
        <mesh geometry={nodes.Object_32.geometry} material={materials.Wheel} />
        <mesh geometry={nodes.Object_33.geometry} material={materials.Wheel} />
      </group>
    </group>
  )
}

useGLTF.preload('/car-gnx.glb')
export default CarModel;